# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
env:
  MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}

jobs:
  test:
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [22.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - run: npm ci
      - run: npx jest --forceExit *.test.js

  # deploy:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     id-token: write
  #   steps:
  #     - uses: actions/checkout@v4

  #     # Setup Node.js environment
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "20.x"
  #         registry-url: "https://registry.npmjs.org"

  #     # Install dependencies
  #     - run: npm install

  #     # Publish to npm if tests pass
  #     - run: npm publish --provenance --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
