name: Tests (main) & Deployment

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed  # Detects merged PRs

env:
  MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_STRING }}

jobs:
  test-ubuntu-node-18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm install jest npm install --save-dev @babel/preset-env @babel/core babel-jest
      - run: npx jest --forceExit mongodb.test.js

  # (Other test jobs remain unchanged)

  deploy:
    needs: test-macos-node-22
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - run: npm install

      # Publish to npm if tests pass
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
