name: Tests on dev branch

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_STRING }}

jobs:
  test-ubuntu-node-18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npx jest --forceExit memory.test.js
      - run: npx jest --forceExit file.test.js

  test-ubuntu-node-20:
    runs-on: ubuntu-latest
    needs: test-ubuntu-node-18
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npx jest --forceExit memory.test.js
      - run: npx jest --forceExit file.test.js

  test-ubuntu-node-22:
    runs-on: ubuntu-latest
    needs: test-ubuntu-node-20
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: npx jest --forceExit memory.test.js
      - run: npx jest --forceExit file.test.js

  test-windows-node-18:
    runs-on: windows-latest
    needs: test-ubuntu-node-22
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npx jest --forceExit memory.test.js
      - run: npx jest --forceExit file.test.js

  test-windows-node-20:
    runs-on: windows-latest
    needs: test-windows-node-18
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npx jest --forceExit memory.test.js
      - run: npx jest --forceExit file.test.js

  test-windows-node-22:
    runs-on: windows-latest
    needs: test-windows-node-20
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: npx jest --forceExit memory.test.js
      - run: npx jest --forceExit file.test.js

  test-macos-node-18:
    runs-on: macos-latest
    needs: test-windows-node-22
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npx jest --forceExit memory.test.js
      - run: npx jest --forceExit file.test.js

  test-macos-node-20:
    runs-on: macos-latest
    needs: test-macos-node-18
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npx jest --forceExit memory.test.js
      - run: npx jest --forceExit file.test.js

  test-macos-node-22:
    runs-on: macos-latest
    needs: test-macos-node-20
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm install jest npm install --save-dev @babel/preset-env @babel/core babel-jest
      - run: npx jest --forceExit memory.test.js
      - run: npx jest --forceExit file.test.js
